language: node_js
node_js:
  - "6"
  - "5"
before_install:
  - wget https://s3.amazonaws.com/mapbox/osm-qa-tiles/latest.country/liechtenstein.mbtiles.gz
  - gunzip liechtenstein.mbtiles.gz
script:
  - node index.js -m liechtenstein.mbtiles -o postbox.geojson --filter '["all", ["==", "amenity", "post_box"], ["$type", "==", "Point"]]'
